export const multiObj1 = {
    id: 'services',
    multiInfoH1: 'Multi Info Section',
    card1Title: 'Title 1',
    card2Title: 'Title 2',
    card3Title: 'Title 3',
    card1Text: 'Placeholder text to reduce typing in card 1',
    card2Text: 'Placeholder text to reduce typing in card 2',
    card3Text: 'Placeholder text to reduce typing in card 3',
    lightBg: true,
    cardTitleDark: true,
    cardTextDark: false,
    img1: require('../../images/svg-1.svg').default,
    img2: require('../../images/svg-2.svg').default,
    img3: require('../../images/svg-3.svg').default,
    alt1: 'alt1',
    alt2: 'alt2',
    alt3: 'alt3',
}