export const multiObj1 = {
    id: 'coming-soon',
    multiInfoH1: 'What I am working on now',
    card1Title: 'Fine Tuning',
    card2Title: 'Other Pages',
    card3Title: 'Security',
    card1Text: 'The pages I have now still need work! This is a work in progress afterall! I have some cool plans for this project!',
    card2Text: 'This is just the main page! I also have the BLOG list and article page set up currently. I am always creating more!',
    card3Text: 'I love the security and encryption side of tech! I always want to make sure everything is as secure as possible.',
    lightBg: true,
    cardTitleDark: true,
    cardTextDark: false,
    img1: require('../../images/svg-1.svg').default,
    img2: require('../../images/colab_board.svg').default,
    img3: require('../../images/svg-4.svg').default,
    alt1: 'alt1',
    alt2: 'alt2',
    alt3: 'alt3',
}