export const multiObj1 = {
    id: 'coming-soon',
    multiInfoH1: 'What I am working on now',
    card1Title: 'A backend',
    card2Title: 'Other Pages',
    card3Title: 'Security',
    card1Text: 'In order for me to make the BLOG and dynamic projects section, I need a backend and database to store it all!',
    card2Text: 'This is currently the only page for the site. I want to add more so that I can create more content and expand!',
    card3Text: 'I love the security and encryption side of tech! I want to be able to make sure that everything is secure!',
    lightBg: true,
    cardTitleDark: true,
    cardTextDark: false,
    img1: require('../../images/svg-1.svg').default,
    img2: require('../../images/colab_board.svg').default,
    img3: require('../../images/svg-4.svg').default,
    alt1: 'alt1',
    alt2: 'alt2',
    alt3: 'alt3',
}