export const infoObj1 = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headLine: 'I am addicted to tech',
    description: 'My name is Peter. I am an all around IT nerd who gets excited with all of the different tech options in the world. When i am not trying to learn I help run an online gaming community with some of my closest friends. This site is currently the minimal viable product. i wanted to get it live as inspiration for me to keep growing my skills as I develop the site.',
    buttonLabel: 'Button Text',
    imgStart: false,
    img: require('../../images/about_me.svg').default,
    alt: 'alt',
    dark: true,
    primary: true,
    darkText: false,
    buttonEnable: false,
    localButton: true,
    buttonPath: 'home'
}

export const infoObj2 = {
    id: 'blog',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'My BLOG',
    headLine: 'Currently not in working order.',
    description: 'I am still building this site and the BLOG section and pages have not been added yet. I have this site code as a public repository on my github page if you are interested in watching my progress.',
    buttonLabel: 'Go to my Github',
    imgStart: true,
    img: require('../../images/blog_content.svg').default,
    alt: 'alt',
    dark: false,
    primary: false,
    darkText: true,
    buttonEnable: true,
    localButton: false,
    buttonPath: '//github.com/sirofwalls/'
}

export const infoObj3 = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'My Projects',
    headLine: 'This is the first!',
    description: 'This is my first official project! This section is not working right now either, but it is being worked on! If you wnt me to help you with your project so i can show off my skills let me know!',
    buttonLabel: 'Button Text',
    imgStart: false,
    img: require('../../images/project_coming.svg').default,
    alt: 'alt',
    dark: true,
    primary: true,
    darkText: false,
    buttonEnable: false,
    localButton: true,
    buttonPath: 'about',
}